name: transporte_vial_rd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  go_router: ^13.2.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.12.3
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  webview_flutter: ^4.10.0
  flutter_polyline_points: ^2.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/fallback_map.png